server:
  port: 8089

eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://eureka-7900.com:7900/eureka/
    healthcheck:
      enabled: true


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/salyfan/config.git
      label: master
#可以远程关闭服务节点
#  management.endpoint.shutdown.enabled=true

  #可以上报服务的真实健康状态
 # eureka.client.healthcheck.enabled=true




